[package]
name = "stake-cw20-gov"
version = "0.2.0"
authors = ["Ben2x4 <ben2x4@tutanota.com>"]
edition = "2018"
description = "CosmWasm-20 compliant token with checkpointing to enable DAOs"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw2 = { version = "0.11" }
cw20 = { version = "0.11" }
stake-cw20 = { path = "../stake-cw20", version = "0.2.0", features = ["library"]  }
cw20-base = {  version = "0.11", features = ["library"] }
cw-storage-plus = { version = "0.11" }
cw-utils = { version = "0.11" }
cosmwasm-std = { version = "1.0.0-beta" }
schemars = "0.8.6"
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.30" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta" }
cw-multi-test = {  version = "0.11" }
anyhow = { version = "1.0.51"}
