[workspace]
members = [
	"contracts/dao-core",
	"contracts/proposal/*",
	"contracts/pre-propose/*",
	"contracts/staking/*",
	"contracts/voting/*",
	"packages/*",
	"test-contracts/*",
	"ci/*",
	"contracts/external/*"
	]
exclude = ["ci/configs/"]

[profile.release.package.stake-cw20-external-rewards]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'
incremental = false
# Please do not disable these. Doing so will cause overflow checks in
# all workspace members to stop working. Overflows should be errors.
overflow-checks = true

[workspace.dependencies]
cosmwasm-std = { version = "1.1", features = ["ibc3"] }
cosmwasm-storage = { version = "1.1" }
cosmwasm-schema = { version = "1.1" }
cw-utils = "0.16"
thiserror = { version = "1.0.30" }
cw-storage-plus = "0.16"
cw2 = "0.16"
cw20 = "0.16"
cw721 = "0.16"
cw20-base = "0.16"
cw-core-v1 = { package = "cw-core", version = "0.1.0", git = "https://github.com/DA0-DA0/dao-contracts.git", tag = "v1.0.0" }
cw-multi-test = "0.16"
cw721-base = "0.16"
cw-controllers = "0.16"
anyhow = { version = "1.0.51"}
cw4-group = "0.16"
rand = "0.8"
cw4 = "0.16"
cw3 = "0.16"
indexmap = "1.9"
serde = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["derive"] }

cw-admin-factory = { path = "./contracts/external/cw-admin-factory" }
dao-core = { path = "./contracts/dao-core" }

dao-proposal-single = { path = "./contracts/proposal/dao-proposal-single" }
dao-proposal-multiple = { path = "./contracts/proposal/dao-proposal-multiple" }
dao-pre-propose-single = { path = "./contracts/pre-propose/dao-pre-propose-single" }
dao-pre-propose-multiple = { path = "./contracts/pre-propose/dao-pre-propose-multiple" }
dao-pre-propose-approval-single = { path = "./contracts/pre-propose/dao-pre-propose-approval-single" }
dao-pre-propose-approver = { path = "./contracts/pre-propose/dao-pre-propose-approver" }
cw20-stake = { path = "./contracts/staking/cw20-stake" }
dao-voting-cw4 = { path = "./contracts/voting/dao-voting-cw4" }
dao-voting-cw20-staked = { path = "./contracts/voting/dao-voting-cw20-staked" }
dao-voting-native-staked = { path = "./contracts/voting/dao-voting-native-staked" }
dao-voting-cw721-staked = { path = "./contracts/voting/dao-voting-cw721-staked" }
dao-voting-cw20-balance = { path = "./test-contracts/dao-voting-cw20-balance"}
cw-denom = { path = "./packages/cw-denom" }
cw-hooks = { path = "./packages/cw-hooks" }
cw721-controllers = { path = "./packages/cw721-controllers" }
dao-macros = { path = "./packages/dao-macros" }
dao-pre-propose-base = { path = "./packages/dao-pre-propose-base" }
dao-proposal-hooks = { path = "./packages/dao-proposal-hooks" }
dao-proposal-sudo = { path = "./test-contracts/dao-proposal-sudo" }
dao-testing = { path = "./packages/dao-testing" }
dao-vote-hooks = { path = "./packages/dao-vote-hooks" }
cw-paginate = { path = "./packages/cw-paginate" }
dao-interface = { path = "./packages/dao-interface" }
dao-voting = { path = "./packages/dao-voting" }
cw-proposal-single-v1 = { package = "cw-proposal-single", version = "0.1.0", git = "https://github.com/DA0-DA0/dao-contracts.git", tag = "v1.0.0" }
voting-v1 = { package = "voting", version = "0.1.0", git = "https://github.com/DA0-DA0/dao-contracts.git", tag = "v1.0.0" }
cw-utils-v1 = {package = "cw-utils", version = "0.13"}
