[package]
name = "cw_dao"
version = "0.1.0"
authors = ["Jake Hartnell <jake@stargaze.zone>", "Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Implements a cw20 token governed DAO with multiple voting patterns."
license = "Apache-2.0"
repository = "https://github.com/JakeHartnell/cw-dao"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw0 = {  version = "0.8.1" }
cw2 = { version = "0.8.1" }
cw20 ="0.8.1"
cw20-base = {  version = "0.8.1", features = ["library"] }
cw-storage-plus = {  version = "0.8.1" }
cosmwasm-std = { version = "0.16.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
cw-multi-test = {  version = "0.8.1" }
