[workspace]
members = ["contracts/*"]

[profile.release.package.cw3-dao]
codegen-units = 1
incremental = false

[profile.release.package.cw3-flex-multisig]
codegen-units = 1
incremental = false

[profile.release.package.cw20-staking]
codegen-units = 1
incremental = false

[profile.release.package.cw-distribution]
codegen-units = 1
incremental = false

[profile.release.package.cw20-gov]
codegen-units = 1
incremental = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'
incremental = false
overflow-checks = true
