[package]
name = "cwd-testing"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "Testing helper functions and interfaces for testing DAO modules."

# This crate depends on multi-test and rand. These are not features in
# wasm builds of cosmwasm. Despite this crate only being used as a dev
# dependency, because it is part of the workspace it will always be
# compiled. There is no good way to remove a member from a workspace
# conditionally. As such, we don't compile anything here if we're
# targeting wasm.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = { workspace = true }
cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
cw20-base = { workspace = true }
cw4 = { workspace = true }
cw4-group = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }

cw20-stake = { workspace = true }
cwd-voting = { workspace = true }
cwd-voting-cw4 = { workspace = true }
cwd-voting-cw20-balance = { workspace = true }
cwd-voting-cw20-staked = { workspace = true }
cwd-hooks = { workspace = true }
cwd-core = { workspace = true, features = ["library"] }
cosmwasm-schema = { version = "1.0.0" }
cwd-interface = { workspace = true }
cwd-pre-propose-single = { workspace = true }
cwd-pre-propose-multiple = { workspace = true }
cw-proposal-single-v1 = { workspace = true }
voting-v1 = { workspace = true }
cwd-proposal-single = { workspace = true }
cwd-voting-cw721-staked = { workspace = true }
cwd-voting-native-staked = { workspace = true }
cw721-base = { workspace = true }