[package]
name = "cwd-proposal-multiple"
version = "0.2.0"
authors = ["blue-note"]
edition = "2021"
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A DAO DAO proposal module for multiple choice (a or b or c or ...) voting."
exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3"] }
cosmwasm-storage = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw3 = { workspace = true }
thiserror = { version = "1.0" }
cwd-core = { workspace = true, features = ["library"] }
cwd-macros = { workspace = true }
cwd-pre-propose-base = { workspace = true }
cwd-interface = { workspace = true }
cwd-voting = { workspace = true }
cwd-hooks = { workspace = true }
cwd-proposal-hooks = { workspace = true }
cwd-vote-hooks = { workspace = true }
cwd-pre-propose-multiple = { workspace = true }
voting-v1 = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
cwd-voting-cw4 = { workspace = true }
cwd-voting-cw20-balance = { workspace = true }
cwd-voting-cw20-staked = { workspace = true }
cwd-voting-native-staked = { workspace = true }
cwd-voting-cw721-staked = { workspace = true }
cw-denom = { workspace = true }
cwd-testing = { workspace = true }
cw20-stake = { workspace = true }
cw20-base = { workspace = true }
cw721-base = { workspace = true }
cw4 = { workspace = true }
cw4-group = { workspace = true }
rand = { workspace = true }
