[package]
name = "cw-pre-propose-base"
version = "0.1.0"
authors = ["ekez <ekez@withoutdoing.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query WASM exports
library = []

[dependencies]
cosmwasm-std = "1.0.0"
cosmwasm-storage = "1.0.0"
cw-storage-plus = "0.13.2"
cw2 = "0.13.2"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
voting = { version = "*", path = "../voting" }
proposal-hooks = { version = "*", path = "../proposal-hooks" }
cw-core-interface = { version = "*", path = "../cw-core-interface" }
cw-denom = { version = "*", path = "../cw-denom" }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
cw-multi-test = "0.13.2"
