[package]
name = "cwd-vote-hooks"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for managing vote hooks."

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cwd-hooks = { workspace = true }
cwd-voting = { workspace = true }