[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

# This crate depends on rand. These are not features in
# wasm builds of cosmwasm. Despite this crate only being used as a dev
# dependency, because it is part of the workspace it will always be
# compiled. There is no good way to remove a member from a workspace
# conditionally. As such, we don't compile anything here if we're
# targeting wasm.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cosm-orc = { version = "2.3.1" }
cw20 = "0.13"
cw20-base = "0.13"
cw-utils = "0.13"
cosmwasm-std = { version = "1.0.0", features = ["ibc3"] }

cwd-core = { path = "../../contracts/cwd-core" }
cw20-stake = { path = "../../contracts/staking/cw20-stake" }
cwd-voting-cw20-staked = { path = "../../contracts/voting/cwd-voting-cw20-staked" }
cwd-proposal-single = { path = "../../contracts/proposal/cwd-proposal-single" }
cwd-pre-propose-single = { path = "../../contracts/pre-propose/cwd-pre-propose-single" }
cwd-interface = { path = "../../packages/cwd-interface" }
cwd-voting = { path = "../../packages/cwd-voting" }

assert_matches = "1.5"
anyhow = { version = "1.0.51"}
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
once_cell = "1.13.0"
env_logger = "0.9.0"
test-context = "0.1.4"
rand = "0.8.5"
