[package]
name = "dao-voting"
version = "2.0.0-beta"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "Types and methods for CosmWasm DAO voting."

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
thiserror = { workspace = true }
cw20 = { workspace = true }
dao-interface = { workspace = true }
dao-macros = { workspace = true }
dao-core = { workspace = true }
cw-denom = { workspace = true }
cw-utils = { workspace = true }
cw-storage-plus = { workspace = true }
