[package]
name = "testing"
version = "0.2.0"
edition = "2021"

# This crate depends on multi-test and rand. These are not features in
# wasm builds of cosmwasm. Despite this crate only being used as a dev
# dependency, because it is part of the workspace it will always be
# compiled. There is no good way to remove a member from a workspace
# conditionally. As such, we don't compile anything here if we're
# targeting wasm.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.8"
cosmwasm-std = { version = "1.0.0" }
voting = { path = "../voting", version = "*" }
cw-multi-test = {  version = "0.13" }
cw20-base = "0.13"
cw4 = "0.13"
cw4-group = "0.13"
cw-utils = "0.13"
cw2 = "0.13"
cw20 = "0.13"
cw20-stake = { path = "../../contracts/cw20-stake", version = "*" }
cw4-voting = { path = "../../contracts/cw4-voting", version = "*" }
cw20-balance-voting = { path = "../../debug/cw20-balance-voting", version = "*" }
cw20-staked-balance-voting = { path = "../../contracts/cw20-staked-balance-voting", version = "*" }
indexable-hooks = { version = "*", path = "../indexable-hooks" }
cw-core = { path = "../../contracts/cw-core", version = "*", features = ["library"] }
cosmwasm-schema = { version = "1.0.0" }
cw-core-interface = { version = "*", path = "../cw-core-interface" }


