[package]
name = "cwd-voting-cw721-staked"
version = "0.2.0"
authors = ["CypherApe cypherape@protonmail.com"]
edition = "2021"
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A DAO DAO voting module based on staked cw721 tokens."

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw-controllers = { workspace = true }
cwd-macros = { workspace = true }
cwd-interface = { workspace = true }
cw721-controllers = { workspace = true }
cw-paginate = { workspace = true }
cw721 = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cw721-base = { workspace = true }
cw-multi-test = { workspace = true }
anyhow = { workspace = true }
cwd-testing = { workspace = true }
