[package]
name = "cwd-macros"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package macros for deriving DAO module interfaces."

[lib]
proc-macro = true

[dependencies]
cosmwasm-schema = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
cwd-interface = { workspace = true }
cwd-hooks = { workspace = true }
cwd-voting = { workspace = true }
cosmwasm-std = { workspace = true }
