[package]
name = "cwd-hooks"
version = "0.2.0"
edition = "2021"
authors = ["Callum Anderson <callumanderson745@gmail.com>"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for managing a set of hooks which can be accessed by their index."

[dependencies]

thiserror = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
