[package]
name = "cw-denom"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for validation and handling of cw20 and native Cosmos SDK denominations."

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }

thiserror = { workspace = true }
cw20 = { workspace = true }

[dev-dependencies]
cw20-base = { workspace = true }
cw-multi-test = { workspace = true }
