[package]
name = "cw-denom"
version = "0.1.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "Package for validation and handling of cw20 and native Cosmos SDK denominations."

[dependencies]
cosmwasm-std = "1.0"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cw20 = "0.13"
