[package]
name = "dao-macros"
version = "2.0.0-beta"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package macros for deriving DAO module interfaces."

[lib]
proc-macro = true

[dependencies]
cosmwasm-schema = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
dao-interface = { workspace = true }
cw-hooks = { workspace = true }
dao-voting = { workspace = true }
cosmwasm-std = { workspace = true }
