[package]
name = "dao-vote-hooks"
version = "2.0.0-beta"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for managing vote hooks."

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-hooks = { workspace = true }
dao-voting = { workspace = true }
