[package]
name = "cwd-proposal-single"
version = "0.2.0"
authors = ["ekez <ekez@withoutdoing.com>"]
edition = "2021"
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A DAO DAO proposal module for single choice (yes / no) voting."

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3"] }
cosmwasm-storage = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw3 = { workspace = true }
thiserror = { workspace = true }
cwd-core = { workspace = true, features = ["library"] }
cwd-macros = { workspace = true }
cwd-pre-propose-base = { workspace = true }
cwd-pre-propose-single = { workspace = true }
cwd-interface = { workspace = true }
cwd-voting = { workspace = true }
cwd-hooks = { workspace = true }
cwd-proposal-hooks = { workspace = true }
cwd-vote-hooks = { workspace = true }

cw-utils-v1 = { workspace = true}
voting-v1 = { workspace = true }
cw-proposal-single-v1 = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
cw-multi-test = { workspace = true }
cwd-voting-cw4 = { workspace = true }
cwd-voting-cw20-balance = { workspace = true }
cwd-voting-cw20-staked = { workspace = true }
cwd-voting-native-staked = { workspace = true }
cwd-voting-cw721-staked = { workspace = true }
cwd-pre-propose-single = { workspace = true }
cw-denom = { workspace = true }
cwd-testing = { workspace = true }
cw20-stake = { workspace = true }
cw20-base = { workspace = true }
cw721-base = { workspace = true }
cw4 = { workspace = true }
cw4-group = { workspace = true }
