name: coverage
'on':
  - push
jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: 'xd009642/tarpaulin:develop-nightly'
      options: '--security-opt seccomp=unconfined'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate code coverage
        run: >
          cargo +nightly tarpaulin --verbose --workspace --out Xml --exclude integration_tests --exclude-files debug/* *test*.rs packages/testing/* packages/cw-core-macros/* legacy/* ci/*
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
