on: [push, pull_request]

name: Typescript Codegen

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn --cwd ./typescript install --frozen-lockfile
      - name: Yarn build
        run: yarn --cwd ./typescript build
      - name: Yarn codegen
        run: yarn --cwd ./typescript codegen
      - name: Show ts changes
        run: git status --porcelain
      - name: Check for ts changes
        # fails if any changes not committed
        run: test -z "$(git status --porcelain)"
